// frontend/src/app/clientLayout.js
//FILE TO PROVIDE REDUX STORE TO THE APP
//Generated by CHATGPT
// A Simple but Effective layout to provide Redux store to the app
//Made to fix issues with "use client" in multiple files
'use client';
import { Provider } from 'react-redux';
import { store } from '../redux/store';

export default function ClientLayout({ children }) {
  return <Provider store={store}>{children}</Provider>;
}
